# Generated by Django 4.1 on 2022-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.TextField(max_length=1000),
        ),
    ]
